### PR TITLE
Added documentation for Attachments

### LINKED ISSUE #519: Add storybook documentation for file attachments.
Part of #456
- Add a story for `Attachments` component with and without using the `Editor` component.

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #519 

**Description**

- Added: storybook documentation for _Attachments_
- Fixed: condition to activate drop zone for files

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Comment by gaagul** [comment]
@AbhayVAshokan I could not create the gifs for the documentation as online converters were saying video format is not being supported, I am currently looking into it.

**Comment by gaagul** [comment]
@gaagul _a

**Comment by AbhayVAshokan** [comment]
@gaagul I use a software called LICEcap for creating GIFs. You can give it a try.
https://www.cockos.com/licecap/

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please let me know if I have to make any changes to the documentation apart from adding GIFS.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a nicely done. Here are a few suggestions.

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have made the suggested changes and also added GIF.

**Review by AbhayVAshokan — APPROVED** [review]
Awesome

**Pull request merged**
