### PR TITLE
Content specific stylesheet added

### PR DESCRIPTION
**Pull request by labeebklatif**
Added separate stylesheet for editor content and editor interface
Editor content styles can be used for bundling and export
Changed the code in fixed menu to codeblock

### CODE REVIEW

**Comment by labeebklatif** [comment]
Added highlight.js for output code highlighting
Added EditorContent component which works as wrapper for editor output for styling
Implemented a feature to add empty paragraph line below the content when clicking outside the last block element like Blockquote or Codeblock

Fixes #53
Fixes #55 

@amaldinesh7 _a Please review

**Comment by amaldinesh7** [comment]
@labeebklatif _a Please make the changes as discussed

**Comment by amaldinesh7** [comment]
@goutham-subramanyam Can you please review the styles?

**Comment by amaldinesh7** [comment]
Changes discussed:
- Change the link embedding prompt to dropdown
- Decrease the height of / command menu and add scroll inside
- Improve font size selector as discussed

**Comment by labeebklatif** [comment]
Changed the link embedding dropdown
Improved font size selector to highlight selected node
Added container div with content class to the editor output
added script to hightlight content code blocks

@amaldinesh7 _a Please review

**Comment by amaldinesh7** [comment]
Point to check:

- Verify the SCSS content
- Verify the usage of EditorContent

Merging for now.

**Pull request merged**
