### PR TITLE
Added feature to edit content variables

### LINKED ISSUE #554: Add ability to edit Editor content variables
image
In the above example, update values in the message box (OrderId, RefundAmount, ReasonForRefund, AmountPaid) whenever the variables are updated.

@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #554 

**Description**

- Added: a `variables` prop inside _EditorContent_ to replace variables with respective values
- Changed: documentation to reflect the changes in the feature

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — COMMENTED** [review]
@gaagul_a 
1. Update the `types.d.ts` file with the newly added prop.
2. https://vimeo.com/790443827/879e1d25f7

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please review the changes.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a plase have a look. The feature is not working as of now: https://vimeo.com/790680172/54a484d077

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please review the changes and let me know if any further changes have to be made to the documentation.

**Review by AbhayVAshokan — APPROVED** [review]

**Comment by AbhayVAshokan** [comment]
@prasidhprabudhan you can use the required feature by updating neetoEditor to the latest version. Pass a `variables` prop to the `EditorContent` component. It is the same structure as the `variables` prop passed to the `Editor` component. Each object will have an optional `value` key. If the `value` is present, it will be replaced with `value` instead of `key`.

**Pull request merged**
