### PR TITLE
Separate css file for editor output

### LINKED ISSUE #58: Configure webpack to split the output
configure webpack to split the CSS and js in order to get the importable CSS and js file which styles the editor output
@amaldinesh7 _a

### PR DESCRIPTION
**Pull request by amaldinesh7**
Fixes #58 

- Moved the build files to the build folder
- Created the CSS file under dist folder that needs to be used externally

@edwinbbu _a Please review

### CODE REVIEW

**Comment by edwinbbu** [comment]
@amaldinesh7 _a Can you test out the branch in neetoChangelog and create a recording.

**Comment by amaldinesh7** [comment]
@edwinbbu _a Please take a look at the video https://vimeo.com/651713157/4d06aa9627

**Comment by amaldinesh7** [comment]
@edwinbbu Please let me know once you verified the changes. I had to push the build in order to test in neeto-changelog. I will remove those build files and update gitignore once you are done with the review.

**Review by edwinbbu — APPROVED** [review]
LGTM!

**Pull request merged**
