### PR TITLE
local image upload UI revamp

### LINKED ISSUE #31: Match UI for neeto-editor image upload with that of design. (Ref - Figma Design)

### PR DESCRIPTION
**Pull request by labeebklatif**
Added new customized progress bar with cancel button
Removed the uppy Dashboard component 
Added the uppy DragDrop component and style customization
Added Modal, Portal, Tab components

Fixes #31 
@karthiknmenon _a Please verify

### CODE REVIEW

**Comment by karthiknmenon** [comment]
@praveen-murali-ind _a Please review the styles.

**Review by karthiknmenon — CHANGES_REQUESTED** [review]
@labeebklatif _a Please check some minor suggestions.

**Comment by labeebklatif** [comment]
Suggested changes done. Build updated. @karthiknmenon _a please verify

**Comment by karthiknmenon** [comment]
@praveen-murali-ind _a Please review.

**Comment by praveen-murali-ind** [comment]
@labeebklatif _a

- [x] Let’s remove the outer border from the Modal content
- [x] Please add a border around the file upload section. Let’s use the border color from this [design](https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=841%3A2180).

Reference 👇

Group 1

//cc @karthiknmenon

**Comment by labeebklatif** [comment]
@praveen-murali-ind _a UI updated with the suggested styles. Please verify

**Review by praveen-murali-ind — APPROVED** [review]
LGTM.

**Review by karthiknmenon — APPROVED** [review]

**Pull request merged**
