### PR TITLE
Added option to receive custom tooltips for menu options as a prop

### LINKED ISSUE #553: Add tooltips prop for customizing the tooltips of menu options
Part of #531 

- Customization of tooltips for menu components by receiving `tooltips` as a prop

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #553 

**Description**

- Added: tooltips prop to receive custom tooltips for menu options

**Checklist**

- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a please add documentation.

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have made the changes, Please review.

**Comment by gaagul** [comment]
I am working on the documentation in the meantime.

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a

**Review by AbhayVAshokan — APPROVED** [review]

**Pull request merged**
