### PR TITLE
Added hot reload to webpack config

### LINKED ISSUE #77: Add hot reload to webpack config
- [x] Update webpack config to allow hot reloading in the development environment.
Ref: https://www.loom.com/share/f7ea753d42b3429e9715bca4207f0604

@AbhayVAshokan _a enhancement _t

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #77
- Updated the webpack config to allow hot reloading in the **development** environment.
- `webpack.config.js` file is not modified since it is only used in production. Necessary modifications are done to `webpack.dev.config.js` and `.babelrc` files to run this feature only in development.

Hot reload demo

**References**
1. [create-react-app webpack configuration](https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/config/webpack.config.js)
2. [react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin)

### CODE REVIEW

**Comment by AbhayVAshokan** [comment]
@edwinbbu _a please have a look. I have added necessary comments wherever there have been major changes.

cc @amaldinesh7

**Comment by AbhayVAshokan** [comment]
@edwinbbu _a: I have made the suggested changes. Please review.

**Comment by edwinbbu** [comment]
@amaldinesh7 _a please check

**Comment by amaldinesh7** [comment]
LGTM!

**Pull request merged**
