### PR TITLE
UI tweaks and Icon changes

### LINKED ISSUE #25: Editor UI tweaks
@labeebklatif _a Please use the following [Figma design file](https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/?node-id=2117%3A3373) as reference for the design and work on the changes. 

cc: @praveen-murali-ind

### PR DESCRIPTION
**Pull request by labeebklatif**
Changed all icons used in Bubble menu, Slash commands, Fixed menu to neeto design icons
Changed the layout styling for mentions
Added avatar support in the mention list
Added prop for controlling avatar visibility in mention list
Improved the variable list, mention list implementation

Fixes #25 

@karthiknmenon _a please review the changes

### CODE REVIEW

**Comment by karthiknmenon** [comment]
@praveen-murali-ind _a Please review the UI changes. 
Ref - [Figma Design](https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=2117%3A3373)

**Comment by labeebklatif** [comment]
@karthiknmenon Forced title support added, issue with mention fixed

**Comment by labeebklatif** [comment]
@karthiknmenon enabled the avatars in the mention suggestion example and updated the sample codes.

**Comment by praveen-murali-ind** [comment]
@labeebklatif _a A few minor changes.

- [x] 1. Please apply the grey background to toolbar as in design (`#E9EBED`), we can use custom CSS for that.
- [x] 2. There is a grouping in toolbar icons. Please check.
- [x] 3. Let’s remove the box-shadow on hover, let’s try this background color on hover `#d8dcde`.
- [x] 4. For Bubble Menu please add the tooltip arrow.
- [x] 5. Let's add a spacing between list items.
- [x] 6. Please match the background colors for the dropdown as well as icons.

Please feel free to ping me if you have any doubts on this.

fixes

//cc @karthiknmenon

**Comment by labeebklatif** [comment]
@praveen-murali-ind _a updated all the suggested changes. please review.

**Comment by praveen-murali-ind** [comment]
@labeebklatif _a LGTM. A few more small changes.

- [x] 1. Let’s add a horizontal scrollbar here for fixing the overflowing content.
- [x] 2. Please add `transition-colors` tailwind class for all action items.
- [x] 3. Let’s use the same padding `p-3` here.
- [x] 4. Please add the `border-radius` `2px` as in the design.
- [x] 5. Please fix the spacing above the `tooltip arrow`.
- [x] 6. Tooltip arrow color should match the bubble menu background color.

UI-fixes

**Comment by labeebklatif** [comment]
@praveen-murali-ind _a all suggested changes are updated. About point 1 - overflow issue: this couldn't be reproduced in my device, but added overflow scroll anyway to the root element. Please verify and let me know the exact scenario if overflow issue still exist.

**Comment by labeebklatif** [comment]
@praveen-murali-ind _a added custom popper dropdown to fix the variable, text size dropdown overflow issues. Please verify.

**Comment by praveen-murali-ind** [comment]
> @praveen-murali-ind _a added custom popper dropdown to fix the variable, text size dropdown overflow issues. Please verify.

LGTM. A minor change.

There are multiple box-shadows applied on dropdown. Please fix.

@labeebklatif _a

Screenshot 2021-11-15 at 8 38 38 PM

**Comment by labeebklatif** [comment]
@praveen-murali-ind _a removed the multi shadow in variable suggestion and fixed the issue with bubble menu border radius

**Review by praveen-murali-ind — APPROVED** [review]
LGTM. @karthiknmenon Please review and merge.

**Comment by praveen-murali-ind** [comment]
@karthiknmenon _a LGTM. Please review and merge.

**Comment by labeebklatif** [comment]
Imported editor menu icons from updated neeto-icons. removed unwanted icon components

**Review by karthiknmenon — APPROVED** [review]
LGTM.

**Pull request merged**
