### PR TITLE
Integrated attachments for editor

### LINKED ISSUE #499: Integrate attachments for neetoEditor
Part of #455 

@saroj990 _a please go through the videos and add your estimate. Let's get on a call if you don't understand any part.

1. https://vimeo.com/781513623/13229d2112
2. https://vimeo.com/781515404/0c37cc1ff4

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #499 

**Description**

- Added: file attachment into neetoEditor
- Changed: styling of editor

**Checklist**

- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**
@AbhayVAshokan _a

### CODE REVIEW

**Comment by gaagul** [comment]
@AbhayVAshokan There is an issue with the slash commands for the attachments, the command is not triggering the file input, Could you please check it out?

**Comment by AbhayVAshokan** [comment]
@gaagul _a please name the PR properly and assign it back to me.

**Comment by gaagul** [comment]
@AbhayVAshokan _a

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
- Rename `onClickAttachment` to `handleUploadAttachments` everywhere.
- I'll take a look at the above-mentioned issue once these reviews are resolved.

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have made the changes as instructed.

I have overriden the border radius using the below class to make the editor look even when fixed menu is active otherwise the border radius of `neeto-editor` class will make the portion just below fixed menu rounded.

`&.fixed-menu-active {
    border: thin solid rgb(var(--neeto-ui-gray-300));
    border-top: none;
    border-radius: 0px;
    border-bottom: none;
  }`

Please let me know if i have to make changes.

**Comment by AbhayVAshokan** [comment]
@gaagul _a have a look at the UI for the three menu different menu types (Fixed, Bubble, and Headless). Border is not necessary for a few of them.

**Comment by gaagul** [comment]
@AbhayVAshokan _a Changes have been made in the styling to conditionally render the bottom border when the fixed menu is active.

**Review by AbhayVAshokan — APPROVED** [review]

**Pull request merged**
