### PR TITLE
Refactored attachment component styling using BEM model

### LINKED ISSUE #513: Update the SCSS styles for the attachments component using BEM conventions
Part of #455 

- [x] Learn the BEM conventions for writing SCSS styles: https://github.com/bigbinary/neeto-engineering-web/tree/main/Front-End-Guidelines/css-guidelines
- [x] Refactor the `_attachments.scss` with proper SCSS conventions.

**UI for reference**
image

spike _t
UI _t

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #513 

**Description**

- Changed: existing CSS into BEM model.

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a nicely done for your first SCSS PR. Please take a look at the following changes.

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please review the changes.

**Review by AbhayVAshokan — APPROVED** [review]
Nicely done. @gaagul _a please make the following changes and assign it back to me.

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have made the changes.

**Pull request merged**
