### PR TITLE
Updated modal component

### LINKED ISSUE #49: Fix issue with Image Upload modal position
Image upload modal appears at inappropriate position (bottom of screen) in certain screens.

### PR DESCRIPTION
**Pull request by labeebklatif**
Added reusable Modal component from neetoUI, removed unwanted dependencies

Fixes #49 
@amaldinesh7 _a Please review

### CODE REVIEW

**Comment by labeebklatif** [comment]
@labeebklatif _a

**Comment by labeebklatif** [comment]
Synced with latest changes from master

@amaldinesh7 _a please review

**Review by amaldinesh7 — CHANGES_REQUESTED** [review]
@labeebklatif _a I've added a few suggestions. Please take a look.

**Comment by labeebklatif** [comment]
@amaldinesh7 _a All suggested changes updated. please verify

**Comment by amaldinesh7** [comment]
LGTM.

**Review by amaldinesh7 — APPROVED** [review]

**Pull request merged**
