### PR TITLE
added font size, font color, image upload options

### LINKED ISSUE #12: Implement static formatting toolbar
@vinay0x _a

### PR DESCRIPTION
**Pull request by labeebklatif**
Fixes #12 

Added general menu option along with font color selection, font variant selection options

### CODE REVIEW

**Comment by labeebklatif** [comment]
@edwinbbu Please review and advice changes if needed

**Comment by edwinbbu** [comment]
@edwinbbu _a

**Comment by edwinbbu** [comment]
@labeebklatif _a Few improvements that can be done. Please look into it.
https://www.loom.com/share/0b4537d972d54c91898ea688f144655a
Ref to a example page discussed in the loom recording - https://jpuri.github.io/react-draft-wysiwyg/#/

**Comment by labeebklatif** [comment]
@edwinbbu _a Updated few changes on the hover styles for menu and added a documentation layout. Please review. Also, thinking about adding a prop details table in next iterations. Please share thoughts on that.

**Pull request merged**
