### PR TITLE
upgraded package for mentions, added custom extension configuration f…

### LINKED ISSUE #20: Allow mentions in editor
@labeebklatif _a In neetoChat, neetoDesk, and other few neeto applications, we would need to allow users to mention other people in `Notes, Comments, etc`. Please look into this issue.

cc: @edwinbbu

### PR DESCRIPTION
**Pull request by labeebklatif**
Added mentions support
- Created custom mention extension configuration
- Changed all defaultOption configuration to addOption function as per latest Tiptap requirement
- Added new renderer component for Mentions List
- Fixed an crash issue while selecting items from Slash commands
Fixes #20 
@karthiknmenon _a please review

### CODE REVIEW

**Review by karthiknmenon — COMMENTED** [review]
@labeebklatif _a Please check the suggestions.

**Comment by labeebklatif** [comment]
@karthiknmenon _a suggested changes are done and added few comments. Please go through them.

**Comment by karthiknmenon** [comment]
@labeebklatif _a A minor suggestion. The rest looks good.

**Comment by labeebklatif** [comment]
@karthiknmenon _a commonly used scss variables are moved to abstracts/_variables.scss as suggested. Please check.

**Review by karthiknmenon — APPROVED** [review]
LGTM.

**Pull request merged**
